### ISSUE TITLE
可以发一下jar文件吗

### ISSUE THREAD

**Issue by Pi-ka7** [Avento/FineReport_channel_Deserialization_Vulnerabilities_RCE#5]
yizhiyu4671@gmail.com

**Comment by Avento** [comment]
> [yizhiyu4671@gmail.com](mailto:yizhiyu4671@gmail.com)

请查阅邮箱

**Comment by Meo9y** [comment]
aabbmeo9y@gmail.com 谢谢大佬 jar包可以发我一份吗

**Comment by Avento** [comment]
> [aabbmeo9y@gmail.com](mailto:aabbmeo9y@gmail.com) 谢谢大佬 jar包可以发我一份吗

已发
